# Generated by Django 5.2.12 on 2026-04-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='species',
            new_name='specie',
        ),
    ]
