# Generated by Django 5.2.12 on 2026-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('doente', 'Doente'), ('vendido', 'Vendido'), ('obito', 'Óbito'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
