# Generated by Django 6.0.3 on 2026-04-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(max_length=50, unique=True, verbose_name='Tag RFID')),
                ('nome', models.CharField(max_length=100, verbose_name='Identificação')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('data_nascimento', models.DateField(verbose_name='Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso (kg)')),
                ('data_pesagem', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='gestao.bovino')),
            ],
            options={
                'ordering': ['-data_pesagem'],
            },
        ),
    ]
