# Generated by Django 6.0.3 on 2026-04-03 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='data_pesagem',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Pesagem'),
        ),
    ]
