# Generated by Django 6.0.3 on 2026-04-03 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_pesagem_data_pesagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bovino',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='bovino',
            name='raca',
        ),
        migrations.AddField(
            model_name='bovino',
            name='status',
            field=models.CharField(default='Ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='rfid_tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PESO', 'Peso (kg)'), ('VACINA', 'Vacina'), ('LEITE', 'Produção Leite (L)'), ('SONO', 'Sono (Horas)'), ('BPM', 'Batimentos (BPM)')], max_length=10)),
                ('valor', models.FloatField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='gestao.bovino')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.DeleteModel(
            name='Pesagem',
        ),
    ]
