# Generated by Django 6.0.3 on 2026-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_bovino_data_nascimento_remove_bovino_raca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Vendido', 'Vendido')], default='Ativo', max_length=20),
        ),
    ]
