# Generated by Django 6.0.3 on 2026-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_bovino_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
