# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('vaccination_plans', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vaccination_date', models.DateField()),
                ('next_vaccination_date', models.DateField(blank=True, help_text='Data da próxima dose recomendada', null=True)),
                ('periodicity', models.IntegerField(blank=True, help_text='Periodicidade em dias', null=True)),
                ('doses_taken', models.IntegerField(blank=True, null=True)),
                ('total_doses', models.IntegerField(blank=True, null=True)),
                ('vaccination_status', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_applications', to='cattle.cow')),
                ('vaccination_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='vaccination_plans.vaccinationplan')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
            options={
                'db_table': 'vaccine_applications',
            },
        ),
    ]
