# Generated by Django 5.2.12 on 2026-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animal_breed'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='animals.animal')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='foods.food')),
            ],
        ),
    ]
