# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('reproductive_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulls', to='breeds.breed')),
            ],
            options={
                'db_table': 'bulls',
                'ordering': ['name'],
            },
        ),
    ]
