# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('cattle', '0001_initial'),
        ('reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='reproduction.birth'),
        ),
        migrations.AddField(
            model_name='cow',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='breeds.breed'),
        ),
    ]
