# Generated by Django 5.2.12 on 2026-10-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='active',
        ),
        migrations.AddField(
            model_name='cow',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=20),
        ),
    ]
