# Generated by Django 5.2.12 on 2026-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models
import django.conf


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animal_breed'),
        ('movement_types', '0001_initial'),
        ('quadrants', '0002_alter_quadrant_area'),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField()),
                ('movement_reason', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='animals.animal')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='movement_types.movementtype')),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_movements', to='quadrants.quadrant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=django.conf.settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
