# Generated by Django 5.2.12 on 2026-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animal_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_production_history', to='animals.animal')),
            ],
        ),
    ]
