# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milkings', to='cattle.cow')),
            ],
            options={
                'db_table': 'milkings',
                'ordering': ['-production_date'],
            },
        ),
    ]
