# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'birth_occurrences',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inseminations', to='cattle.bull')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inseminations', to='cattle.cow')),
            ],
            options={
                'db_table': 'inseminations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='births', to='reproduction.birthoccurrence')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='reproduction.insemination')),
            ],
            options={
                'db_table': 'births',
                'ordering': ['-date'],
            },
        ),
    ]
