# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.IntegerField()),
                ('animal_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='cattle.cattleclass')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='foods.food')),
            ],
        ),
    ]
