# Generated by Django 5.2.12 on 2026-04-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purpose_types', '0001_initial'),
        ('quadrants', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
                ('register_number', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField()),
                ('sex', models.CharField(max_length=1)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purpose_types.purposetype')),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadrants.quadrant')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
        ),
    ]
