# Generated by Django 5.2.12 on 2026-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_species_animal_specie'),
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='breeds.breed'),
        ),
    ]
