# Generated by Django 5.2.12 on 2026-04-08 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_rename_species_animal_specie'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vaccination_date', models.DateField()),
                ('periodicity', models.IntegerField()),
                ('doses_taken', models.IntegerField()),
                ('total_doses', models.IntegerField()),
                ('vaccination_status', models.BooleanField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
        ),
    ]
