# Generated by Django 5.2.12 on 2026-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_plans', '0001_initial'),
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='vaccination_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='vaccination_plans.vaccinationplan'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='doses_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='periodicity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='total_doses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccination_status',
            field=models.BooleanField(default=True),
        ),
    ]
