# Generated by Django 5.2.12 on 2026-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_vaccination_vaccination_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='next_vaccination_date',
            field=models.DateField(blank=True, help_text='Data da próxima dose recomendada', null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='periodicity',
            field=models.IntegerField(blank=True, help_text='Periodicidade em dias', null=True),
        ),
    ]
