# Generated by Django 5.2.12 on 2026-10-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_taken', models.IntegerField(default=0)),
                ('consultation_date', models.DateField()),
                ('consultation_reason', models.TextField()),
            ],
            options={
                'db_table': 'animal_health',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'veterinary_occurrences',
                'ordering': ['description'],
            },
        ),
    ]
