# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal_health', '0001_initial'),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealth',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle.cow'),
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='animal_health.veterinaryoccurrence'),
        ),
    ]
