# Generated by Django 5.2.12 on 2026-05-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0005_migrate_active_to_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(help_text='BPM - Batimentos por minuto')),
                ('sleep_duration', models.DecimalField(decimal_places=2, help_text='Horas de sono nas últimas 24h', max_digits=5)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura corporal em Celsius', max_digits=5, null=True)),
                ('symptoms', models.CharField(blank=True, help_text="Sintomas detectados. Ex: 'Agitação, Tosse, Respiração acelerada'", max_length=500)),
                ('alert_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='normal', max_length=20)),
                ('reading_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_battery', models.IntegerField(blank=True, help_text='Nível de bateria do sensor em %', null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_readings', to='animals.animal')),
            ],
            options={
                'ordering': ['-reading_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnimalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Suspeita de Febre Alta', max_length=200)),
                ('description', models.TextField(help_text='Descrição detalhada do alerta')),
                ('reason', models.CharField(help_text="Por que o alerta foi disparado. Ex: 'Frequência cardíaca 120 BPM + Sono 0 horas'", max_length=500)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='animals.animal')),
                ('biometric_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='animal_biometrics.biometricreading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='biometricreading',
            index=models.Index(fields=['-reading_timestamp'], name='animal_biom_reading_93db9f_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricreading',
            index=models.Index(fields=['animal', '-reading_timestamp'], name='animal_biom_animal__5e58ba_idx'),
        ),
        migrations.AddIndex(
            model_name='animalalert',
            index=models.Index(fields=['-created_at'], name='animal_biom_created_97f55f_idx'),
        ),
        migrations.AddIndex(
            model_name='animalalert',
            index=models.Index(fields=['animal', 'status', '-created_at'], name='animal_biom_animal__d15b38_idx'),
        ),
    ]
