# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal_movements', '0001_initial'),
        ('cattle', '0001_initial'),
        ('movement_types', '0001_initial'),
        ('quadrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmovement',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cattle.cow'),
        ),
        migrations.AddField(
            model_name='animalmovement',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='movement_types.movementtype'),
        ),
        migrations.AddField(
            model_name='animalmovement',
            name='quadrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_movements', to='quadrants.quadrant'),
        ),
        migrations.AddField(
            model_name='animalmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
