# Generated by Django 5.2.12 on 2026-10-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_time', models.DateTimeField()),
                ('meal_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='cattle.cow')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='foods.food')),
            ],
        ),
    ]
